### ISSUE TITLE
Wrong number displayed if using _ as numeric separator

### ISSUE THREAD

**Issue by jeremieflrnt** [coalaura/numnums#1]
Hi, cool extension! thanks for making it!

I'm used to `_` as a numeric separator for better readability:
100000000 = 100_000_000 is still OK in TS.
But the extension display: 100
Can your extension work with `_` ?

**Comment by coalaura** [comment]
I'm struggling to reproduce the issue, do you have a piece of code it happened on?

![weird](https://i.shrt.day/0OOFNNMJZJ.png)

**Comment by coalaura** [comment]
oh wait i missread it

**Comment by coalaura** [comment]
should work fine now, pushed an update :)

![yes](https://i.shrt.day/80UIJNWVJF.png)

**Comment by jeremieflrnt** [comment]
Oh yes, perfect!
Thanks :))
